# Change this to re-enable the workflow
name: Fetch Stock

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch: # enable manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - run: node index.js
        env:
          botToken: ${{ secrets.botToken }}
          chatID: ${{ secrets.chatID }}